name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install Dependencies
        shell: cmd
        run: |
          haxelib setup C:\haxelib
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp --skip-dependencies
          haxelib install lime 8.1.3 --skip-dependencies
          haxelib run lime setup
          haxelib install openfl 9.3.4 --skip-dependencies
          haxelib install flixel 5.6.2 --skip-dependencies
          haxelib install flixel-addons 3.2.3 --skip-dependencies
          haxelib install flixel-ui 2.6.1 --skip-dependencies
          haxelib install thx.semver --skip-dependencies
          haxelib install hxvlc 2.1.4 --skip-dependencies
          haxelib install haxeui-openfl 1.7.0 --skip-dependencies
          haxelib git flxanimate https://github.com/Redar13/flxanimate dev --skip-dependencies
          haxelib git hscript-improved https://github.com/Redar13/hscript-improved polymod-scripted-classes --skip-dependencies
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --skip-dependencies
          haxelib install hxdiscord_rpc --skip-dependencies

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        shell: cmd
        run: haxelib run lime build windows

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TwistEngine_${{github.run_id}}_Windows
          path: export/dev/windows/bin

      - name: Zip Release Build
        if: github.event_name == 'release'
        shell: pwsh
        run: Compress-Archive -Path export/dev/windows/bin/* -DestinationPath TwistEngine-Windows.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: TwistEngine-Windows.zip
